#ifndef _COLOR_H_
#define _COLOR_H_

#define COLOR_DARKGRAY			0xFF2F4F4F
#define COLOR_LIGHTGRAY			0xFFD3D3D3
#define COLOR_BLUE			0xFF0000FF
#define COLOR_DARKSLATEBLUE		0xFF483D8B
#define COLOR_LIGHTSLATEBLE		0xFF8470FF
#define COLOR_CYAN			0xFF00FFFF
#define COLOR_GREEN			0xFF00FF00
#define COLOR_YELLOW			0xFFFFFF00
#define COLOR_GOLD			0xFFFFD700
#define COLOR_BROWN			0xFFA52A2A
#define COLOR_ORANGE			0xFFFFA500
#define COLOR_RED			0xFFFF0000
#define COLOR_PINK			0xFFFFC0CB
#define COLOR_MAROON			0xFFB03060
#define COLOR_VIOLET			0xFFEE82EE
#define COLOR_BLUEVIOLET		0xFF8A2BE2
#define COLOR_GRAY			0xFF808080
#define COLOR_WHITE			0xFFFFFFFF
#define COLOR_BLACK			0xFF000000





#define COLOR_TEXT			COLOR_BLACK

#define BORDER_COLOR			0xFF0F0F0F

#define BUTTON_BORDER_CLR		COLOR_RED
#define BUTTON_RECT_CLR			COLOR_GREEN


#define MENU_BACK_COLOR			COLOR_GREEN
#define MENU_FOCUS_COLOR		COLOR_RED
#define MENU_SEP_COLOR			COLOR_BLUE

#define WINDOW_BORDER_COLOR		COLOR_RED
#define WINDOW_TITLE_BACK_COLOR		COLOR_GRAY	
#define WINDOW_AREA_BACK_COLOR		COLOR_WHITE


#define MOUSE_ICON_COLOR		COLOR_BLUE

#define STATUS_BACK_COLOR		COLOR_CYAN

#define MESSAGEBOX_BORDER_COLOR		COLOR_BLUE
#define MESSAGEBOX_BACK_COLOR		COLOR_GRAY

#define SEEKBAR_BACK_COLOR		COLOR_RED
#define SEEKBAR_FORE_COLOR		COLOR_BLUE

#define SPINNER_BACK_COLOR		COLOR_GRAY
#define SPINNER_ITEM_SEL_COLOR		COLOR_RED
#define SPINNER_ITEM_NOSEL_COLOR	COLOR_WHITE	
#endif
